version: '3.0'
services:
  web:
    image: tomcat
    environment:
    - JPDA_ADDRESS=8000
    ports:
    - "31020:8080"
    - "8000:8000"
    volumes:
    - ./:/usr/local/tomcat/webapps/ROOT/
  database:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=1
    ports:
    - "3306:3306"
    volumes:
    - ./src/Additional/DB:/docker-entrypoint-initdb.d